cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo3_sobol_1007_EXOENZYME.json VPRO/LSQ/vpro_31007_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo3_sobol_119_EXOENZYME.json VPRO/LSQ/vpro_3119_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo3_sobol_135_EXOENZYME.json VPRO/LSQ/vpro_3135_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo3_sobol_151_EXOENZYME.json VPRO/LSQ/vpro_3151_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo3_sobol_163_EXOENZYME.json VPRO/LSQ/vpro_3163_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo3_sobol_199_EXOENZYME.json VPRO/LSQ/vpro_3199_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo3_sobol_200_EXOENZYME.json VPRO/LSQ/vpro_3200_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo3_sobol_223_EXOENZYME.json VPRO/LSQ/vpro_3223_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo3_sobol_239_EXOENZYME.json VPRO/LSQ/vpro_3239_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo3_sobol_23_EXOENZYME.json VPRO/LSQ/vpro_323_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo3_sobol_24_EXOENZYME.json VPRO/LSQ/vpro_324_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo3_sobol_288_EXOENZYME.json VPRO/LSQ/vpro_3288_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo3_sobol_291_EXOENZYME.json VPRO/LSQ/vpro_3291_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo3_sobol_295_EXOENZYME.json VPRO/LSQ/vpro_3295_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo3_sobol_304_EXOENZYME.json VPRO/LSQ/vpro_3304_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo3_sobol_359_EXOENZYME.json VPRO/LSQ/vpro_3359_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo3_sobol_367_EXOENZYME.json VPRO/LSQ/vpro_3367_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo3_sobol_387_EXOENZYME.json VPRO/LSQ/vpro_3387_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo3_sobol_439_EXOENZYME.json VPRO/LSQ/vpro_3439_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo3_sobol_440_EXOENZYME.json VPRO/LSQ/vpro_3440_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo3_sobol_447_EXOENZYME.json VPRO/LSQ/vpro_3447_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo3_sobol_448_EXOENZYME.json VPRO/LSQ/vpro_3448_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo3_sobol_451_EXOENZYME.json VPRO/LSQ/vpro_3451_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo3_sobol_455_EXOENZYME.json VPRO/LSQ/vpro_3455_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo3_sobol_496_EXOENZYME.json VPRO/LSQ/vpro_3496_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo3_sobol_503_EXOENZYME.json VPRO/LSQ/vpro_3503_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo3_sobol_511_EXOENZYME.json VPRO/LSQ/vpro_3511_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo3_sobol_519_EXOENZYME.json VPRO/LSQ/vpro_3519_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo3_sobol_527_EXOENZYME.json VPRO/LSQ/vpro_3527_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo3_sobol_572_EXOENZYME.json VPRO/LSQ/vpro_3572_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo3_sobol_575_EXOENZYME.json VPRO/LSQ/vpro_3575_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo3_sobol_579_EXOENZYME.json VPRO/LSQ/vpro_3579_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo3_sobol_591_EXOENZYME.json VPRO/LSQ/vpro_3591_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo3_sobol_592_EXOENZYME.json VPRO/LSQ/vpro_3592_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo3_sobol_631_EXOENZYME.json VPRO/LSQ/vpro_3631_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo3_sobol_656_EXOENZYME.json VPRO/LSQ/vpro_3656_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo3_sobol_663_EXOENZYME.json VPRO/LSQ/vpro_3663_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo3_sobol_671_EXOENZYME.json VPRO/LSQ/vpro_3671_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo3_sobol_679_EXOENZYME.json VPRO/LSQ/vpro_3679_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo3_sobol_71_EXOENZYME.json VPRO/LSQ/vpro_371_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo3_sobol_727_EXOENZYME.json VPRO/LSQ/vpro_3727_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo3_sobol_728_EXOENZYME.json VPRO/LSQ/vpro_3728_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo3_sobol_760_EXOENZYME.json VPRO/LSQ/vpro_3760_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo3_sobol_768_EXOENZYME.json VPRO/LSQ/vpro_3768_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo3_sobol_807_EXOENZYME.json VPRO/LSQ/vpro_3807_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo3_sobol_816_EXOENZYME.json VPRO/LSQ/vpro_3816_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo3_sobol_823_EXOENZYME.json VPRO/LSQ/vpro_3823_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo3_sobol_87_EXOENZYME.json VPRO/LSQ/vpro_387_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo3_sobol_880_EXOENZYME.json VPRO/LSQ/vpro_3880_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo3_sobol_887_EXOENZYME.json VPRO/LSQ/vpro_3887_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo3_sobol_88_EXOENZYME.json VPRO/LSQ/vpro_388_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo3_sobol_911_EXOENZYME.json VPRO/LSQ/vpro_3911_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo3_sobol_936_EXOENZYME.json VPRO/LSQ/vpro_3936_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo3_sobol_943_EXOENZYME.json VPRO/LSQ/vpro_3943_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo3_sobol_963_EXOENZYME.json VPRO/LSQ/vpro_3963_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo3_sobol_968_EXOENZYME.json VPRO/LSQ/vpro_3968_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo3_sobol_976_EXOENZYME.json VPRO/LSQ/vpro_3976_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo3_sobol_992_EXOENZYME.json VPRO/LSQ/vpro_3992_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo4_sobol_0_EXOENZYME.json VPRO/LSQ/vpro_40_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo4_sobol_108_EXOENZYME.json VPRO/LSQ/vpro_4108_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo4_sobol_124_EXOENZYME.json VPRO/LSQ/vpro_4124_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo4_sobol_131_EXOENZYME.json VPRO/LSQ/vpro_4131_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo4_sobol_192_EXOENZYME.json VPRO/LSQ/vpro_4192_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo4_sobol_199_EXOENZYME.json VPRO/LSQ/vpro_4199_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo4_sobol_204_EXOENZYME.json VPRO/LSQ/vpro_4204_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo4_sobol_212_EXOENZYME.json VPRO/LSQ/vpro_4212_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo4_sobol_244_EXOENZYME.json VPRO/LSQ/vpro_4244_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo4_sobol_28_EXOENZYME.json VPRO/LSQ/vpro_428_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo4_sobol_299_EXOENZYME.json VPRO/LSQ/vpro_4299_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo4_sobol_303_EXOENZYME.json VPRO/LSQ/vpro_4303_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo4_sobol_339_EXOENZYME.json VPRO/LSQ/vpro_4339_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo4_sobol_340_EXOENZYME.json VPRO/LSQ/vpro_4340_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo4_sobol_35_EXOENZYME.json VPRO/LSQ/vpro_435_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo4_sobol_403_EXOENZYME.json VPRO/LSQ/vpro_4403_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo4_sobol_444_EXOENZYME.json VPRO/LSQ/vpro_4444_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo4_sobol_479_EXOENZYME.json VPRO/LSQ/vpro_4479_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo4_sobol_499_EXOENZYME.json VPRO/LSQ/vpro_4499_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo4_sobol_511_EXOENZYME.json VPRO/LSQ/vpro_4511_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo4_sobol_519_EXOENZYME.json VPRO/LSQ/vpro_4519_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo4_sobol_563_EXOENZYME.json VPRO/LSQ/vpro_4563_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo4_sobol_575_EXOENZYME.json VPRO/LSQ/vpro_4575_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo4_sobol_636_EXOENZYME.json VPRO/LSQ/vpro_4636_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo4_sobol_639_EXOENZYME.json VPRO/LSQ/vpro_4639_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo4_sobol_672_EXOENZYME.json VPRO/LSQ/vpro_4672_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo4_sobol_684_EXOENZYME.json VPRO/LSQ/vpro_4684_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo4_sobol_707_EXOENZYME.json VPRO/LSQ/vpro_4707_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo4_sobol_755_EXOENZYME.json VPRO/LSQ/vpro_4755_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo4_sobol_768_EXOENZYME.json VPRO/LSQ/vpro_4768_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo4_sobol_76_EXOENZYME.json VPRO/LSQ/vpro_476_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo4_sobol_780_EXOENZYME.json VPRO/LSQ/vpro_4780_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo4_sobol_796_EXOENZYME.json VPRO/LSQ/vpro_4796_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo4_sobol_828_EXOENZYME.json VPRO/LSQ/vpro_4828_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo4_sobol_831_EXOENZYME.json VPRO/LSQ/vpro_4831_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo4_sobol_864_EXOENZYME.json VPRO/LSQ/vpro_4864_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo4_sobol_892_EXOENZYME.json VPRO/LSQ/vpro_4892_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo4_sobol_916_EXOENZYME.json VPRO/LSQ/vpro_4916_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo4_sobol_92_EXOENZYME.json VPRO/LSQ/vpro_492_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo4_sobol_95_EXOENZYME.json VPRO/LSQ/vpro_495_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo4_sobol_976_EXOENZYME.json VPRO/LSQ/vpro_4976_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_EXOENZYME/out/lsq_ponly_EXOENZYME_shgo4_sobol_988_EXOENZYME.json VPRO/LSQ/vpro_4988_EXOENZYME.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo3_sobol_101_MIN.json VPRO/LSQ/vpro_3101_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo3_sobol_106_MIN.json VPRO/LSQ/vpro_3106_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo3_sobol_121_MIN.json VPRO/LSQ/vpro_3121_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo3_sobol_134_MIN.json VPRO/LSQ/vpro_3134_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo3_sobol_137_MIN.json VPRO/LSQ/vpro_3137_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo3_sobol_166_MIN.json VPRO/LSQ/vpro_3166_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo3_sobol_181_MIN.json VPRO/LSQ/vpro_3181_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo3_sobol_185_MIN.json VPRO/LSQ/vpro_3185_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo3_sobol_186_MIN.json VPRO/LSQ/vpro_3186_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo3_sobol_197_MIN.json VPRO/LSQ/vpro_3197_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo3_sobol_229_MIN.json VPRO/LSQ/vpro_3229_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo3_sobol_245_MIN.json VPRO/LSQ/vpro_3245_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo3_sobol_250_MIN.json VPRO/LSQ/vpro_3250_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo3_sobol_277_MIN.json VPRO/LSQ/vpro_3277_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo3_sobol_282_MIN.json VPRO/LSQ/vpro_3282_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo3_sobol_294_MIN.json VPRO/LSQ/vpro_3294_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo3_sobol_298_MIN.json VPRO/LSQ/vpro_3298_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo3_sobol_322_MIN.json VPRO/LSQ/vpro_3322_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo3_sobol_346_MIN.json VPRO/LSQ/vpro_3346_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo3_sobol_358_MIN.json VPRO/LSQ/vpro_3358_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo3_sobol_37_MIN.json VPRO/LSQ/vpro_337_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo3_sobol_389_MIN.json VPRO/LSQ/vpro_3389_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo3_sobol_390_MIN.json VPRO/LSQ/vpro_3390_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo3_sobol_394_MIN.json VPRO/LSQ/vpro_3394_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo3_sobol_422_MIN.json VPRO/LSQ/vpro_3422_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo3_sobol_42_MIN.json VPRO/LSQ/vpro_342_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo3_sobol_438_MIN.json VPRO/LSQ/vpro_3438_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo3_sobol_450_MIN.json VPRO/LSQ/vpro_3450_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo3_sobol_453_MIN.json VPRO/LSQ/vpro_3453_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo3_sobol_458_MIN.json VPRO/LSQ/vpro_3458_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo3_sobol_474_MIN.json VPRO/LSQ/vpro_3474_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo3_sobol_490_MIN.json VPRO/LSQ/vpro_3490_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo3_sobol_518_MIN.json VPRO/LSQ/vpro_3518_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo3_sobol_521_MIN.json VPRO/LSQ/vpro_3521_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo3_sobol_53_MIN.json VPRO/LSQ/vpro_353_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo3_sobol_566_MIN.json VPRO/LSQ/vpro_3566_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo3_sobol_570_MIN.json VPRO/LSQ/vpro_3570_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo3_sobol_573_MIN.json VPRO/LSQ/vpro_3573_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo3_sobol_582_MIN.json VPRO/LSQ/vpro_3582_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo3_sobol_585_MIN.json VPRO/LSQ/vpro_3585_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo3_sobol_5_MIN.json VPRO/LSQ/vpro_35_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo3_sobol_634_MIN.json VPRO/LSQ/vpro_3634_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo3_sobol_650_MIN.json VPRO/LSQ/vpro_3650_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo3_sobol_665_MIN.json VPRO/LSQ/vpro_3665_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo3_sobol_674_MIN.json VPRO/LSQ/vpro_3674_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo3_sobol_698_MIN.json VPRO/LSQ/vpro_3698_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo3_sobol_710_MIN.json VPRO/LSQ/vpro_3710_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo3_sobol_726_MIN.json VPRO/LSQ/vpro_3726_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo3_sobol_729_MIN.json VPRO/LSQ/vpro_3729_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo3_sobol_738_MIN.json VPRO/LSQ/vpro_3738_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo3_sobol_73_MIN.json VPRO/LSQ/vpro_373_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo3_sobol_746_MIN.json VPRO/LSQ/vpro_3746_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo3_sobol_770_MIN.json VPRO/LSQ/vpro_3770_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo3_sobol_793_MIN.json VPRO/LSQ/vpro_3793_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo3_sobol_809_MIN.json VPRO/LSQ/vpro_3809_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo3_sobol_825_MIN.json VPRO/LSQ/vpro_3825_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo3_sobol_89_MIN.json VPRO/LSQ/vpro_389_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo4_sobol_1022_MIN.json VPRO/LSQ/vpro_41022_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo4_sobol_129_MIN.json VPRO/LSQ/vpro_4129_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo4_sobol_142_MIN.json VPRO/LSQ/vpro_4142_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo4_sobol_158_MIN.json VPRO/LSQ/vpro_4158_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo4_sobol_174_MIN.json VPRO/LSQ/vpro_4174_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo4_sobol_198_MIN.json VPRO/LSQ/vpro_4198_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo4_sobol_206_MIN.json VPRO/LSQ/vpro_4206_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo4_sobol_281_MIN.json VPRO/LSQ/vpro_4281_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo4_sobol_289_MIN.json VPRO/LSQ/vpro_4289_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo4_sobol_297_MIN.json VPRO/LSQ/vpro_4297_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo4_sobol_302_MIN.json VPRO/LSQ/vpro_4302_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo4_sobol_30_MIN.json VPRO/LSQ/vpro_430_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo4_sobol_321_MIN.json VPRO/LSQ/vpro_4321_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo4_sobol_366_MIN.json VPRO/LSQ/vpro_4366_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo4_sobol_433_MIN.json VPRO/LSQ/vpro_4433_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo4_sobol_441_MIN.json VPRO/LSQ/vpro_4441_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo4_sobol_446_MIN.json VPRO/LSQ/vpro_4446_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo4_sobol_473_MIN.json VPRO/LSQ/vpro_4473_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo4_sobol_489_MIN.json VPRO/LSQ/vpro_4489_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo4_sobol_497_MIN.json VPRO/LSQ/vpro_4497_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo4_sobol_510_MIN.json VPRO/LSQ/vpro_4510_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo4_sobol_518_MIN.json VPRO/LSQ/vpro_4518_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo4_sobol_529_MIN.json VPRO/LSQ/vpro_4529_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo4_sobol_582_MIN.json VPRO/LSQ/vpro_4582_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo4_sobol_633_MIN.json VPRO/LSQ/vpro_4633_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo4_sobol_657_MIN.json VPRO/LSQ/vpro_4657_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo4_sobol_665_MIN.json VPRO/LSQ/vpro_4665_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo4_sobol_697_MIN.json VPRO/LSQ/vpro_4697_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo4_sobol_6_MIN.json VPRO/LSQ/vpro_46_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo4_sobol_721_MIN.json VPRO/LSQ/vpro_4721_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo4_sobol_729_MIN.json VPRO/LSQ/vpro_4729_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo4_sobol_766_MIN.json VPRO/LSQ/vpro_4766_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo4_sobol_794_MIN.json VPRO/LSQ/vpro_4794_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo4_sobol_81_MIN.json VPRO/LSQ/vpro_481_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo4_sobol_830_MIN.json VPRO/LSQ/vpro_4830_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo4_sobol_854_MIN.json VPRO/LSQ/vpro_4854_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo4_sobol_870_MIN.json VPRO/LSQ/vpro_4870_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo4_sobol_889_MIN.json VPRO/LSQ/vpro_4889_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo4_sobol_934_MIN.json VPRO/LSQ/vpro_4934_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo4_sobol_937_MIN.json VPRO/LSQ/vpro_4937_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo4_sobol_94_MIN.json VPRO/LSQ/vpro_494_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo4_sobol_974_MIN.json VPRO/LSQ/vpro_4974_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIN/out/lsq_ponly_MIN_shgo4_sobol_998_MIN.json VPRO/LSQ/vpro_4998_MIN.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo3_sobol_113_MIXOTROPH.json VPRO/LSQ/vpro_3113_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo3_sobol_14_MIXOTROPH.json VPRO/LSQ/vpro_314_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo3_sobol_166_MIXOTROPH.json VPRO/LSQ/vpro_3166_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo3_sobol_174_MIXOTROPH.json VPRO/LSQ/vpro_3174_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo3_sobol_17_MIXOTROPH.json VPRO/LSQ/vpro_317_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo3_sobol_182_MIXOTROPH.json VPRO/LSQ/vpro_3182_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo3_sobol_22_MIXOTROPH.json VPRO/LSQ/vpro_322_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo3_sobol_230_MIXOTROPH.json VPRO/LSQ/vpro_3230_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo3_sobol_233_MIXOTROPH.json VPRO/LSQ/vpro_3233_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo3_sobol_238_MIXOTROPH.json VPRO/LSQ/vpro_3238_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo3_sobol_246_MIXOTROPH.json VPRO/LSQ/vpro_3246_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo3_sobol_25_MIXOTROPH.json VPRO/LSQ/vpro_325_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo3_sobol_294_MIXOTROPH.json VPRO/LSQ/vpro_3294_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo3_sobol_326_MIXOTROPH.json VPRO/LSQ/vpro_3326_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo3_sobol_330_MIXOTROPH.json VPRO/LSQ/vpro_3330_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo3_sobol_342_MIXOTROPH.json VPRO/LSQ/vpro_3342_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo3_sobol_353_MIXOTROPH.json VPRO/LSQ/vpro_3353_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo3_sobol_358_MIXOTROPH.json VPRO/LSQ/vpro_3358_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo3_sobol_369_MIXOTROPH.json VPRO/LSQ/vpro_3369_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo3_sobol_385_MIXOTROPH.json VPRO/LSQ/vpro_3385_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo3_sobol_398_MIXOTROPH.json VPRO/LSQ/vpro_3398_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo3_sobol_406_MIXOTROPH.json VPRO/LSQ/vpro_3406_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo3_sobol_449_MIXOTROPH.json VPRO/LSQ/vpro_3449_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo3_sobol_454_MIXOTROPH.json VPRO/LSQ/vpro_3454_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo3_sobol_470_MIXOTROPH.json VPRO/LSQ/vpro_3470_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo3_sobol_478_MIXOTROPH.json VPRO/LSQ/vpro_3478_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo3_sobol_490_MIXOTROPH.json VPRO/LSQ/vpro_3490_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo3_sobol_494_MIXOTROPH.json VPRO/LSQ/vpro_3494_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo3_sobol_497_MIXOTROPH.json VPRO/LSQ/vpro_3497_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo3_sobol_537_MIXOTROPH.json VPRO/LSQ/vpro_3537_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo3_sobol_550_MIXOTROPH.json VPRO/LSQ/vpro_3550_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo3_sobol_566_MIXOTROPH.json VPRO/LSQ/vpro_3566_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo3_sobol_574_MIXOTROPH.json VPRO/LSQ/vpro_3574_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo3_sobol_598_MIXOTROPH.json VPRO/LSQ/vpro_3598_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo3_sobol_614_MIXOTROPH.json VPRO/LSQ/vpro_3614_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo3_sobol_62_MIXOTROPH.json VPRO/LSQ/vpro_362_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo3_sobol_630_MIXOTROPH.json VPRO/LSQ/vpro_3630_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo3_sobol_633_MIXOTROPH.json VPRO/LSQ/vpro_3633_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo3_sobol_641_MIXOTROPH.json VPRO/LSQ/vpro_3641_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo3_sobol_646_MIXOTROPH.json VPRO/LSQ/vpro_3646_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo3_sobol_65_MIXOTROPH.json VPRO/LSQ/vpro_365_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo3_sobol_686_MIXOTROPH.json VPRO/LSQ/vpro_3686_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo3_sobol_714_MIXOTROPH.json VPRO/LSQ/vpro_3714_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo3_sobol_734_MIXOTROPH.json VPRO/LSQ/vpro_3734_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo3_sobol_73_MIXOTROPH.json VPRO/LSQ/vpro_373_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo3_sobol_750_MIXOTROPH.json VPRO/LSQ/vpro_3750_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo3_sobol_782_MIXOTROPH.json VPRO/LSQ/vpro_3782_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo3_sobol_78_MIXOTROPH.json VPRO/LSQ/vpro_378_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo3_sobol_790_MIXOTROPH.json VPRO/LSQ/vpro_3790_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo4_sobol_1000_MIXOTROPH.json VPRO/LSQ/vpro_41000_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo4_sobol_108_MIXOTROPH.json VPRO/LSQ/vpro_4108_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo4_sobol_111_MIXOTROPH.json VPRO/LSQ/vpro_4111_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo4_sobol_112_MIXOTROPH.json VPRO/LSQ/vpro_4112_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo4_sobol_187_MIXOTROPH.json VPRO/LSQ/vpro_4187_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo4_sobol_188_MIXOTROPH.json VPRO/LSQ/vpro_4188_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo4_sobol_208_MIXOTROPH.json VPRO/LSQ/vpro_4208_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo4_sobol_224_MIXOTROPH.json VPRO/LSQ/vpro_4224_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo4_sobol_252_MIXOTROPH.json VPRO/LSQ/vpro_4252_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo4_sobol_272_MIXOTROPH.json VPRO/LSQ/vpro_4272_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo4_sobol_287_MIXOTROPH.json VPRO/LSQ/vpro_4287_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo4_sobol_28_MIXOTROPH.json VPRO/LSQ/vpro_428_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo4_sobol_291_MIXOTROPH.json VPRO/LSQ/vpro_4291_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo4_sobol_299_MIXOTROPH.json VPRO/LSQ/vpro_4299_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo4_sobol_320_MIXOTROPH.json VPRO/LSQ/vpro_4320_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo4_sobol_32_MIXOTROPH.json VPRO/LSQ/vpro_432_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo4_sobol_355_MIXOTROPH.json VPRO/LSQ/vpro_4355_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo4_sobol_371_MIXOTROPH.json VPRO/LSQ/vpro_4371_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo4_sobol_379_MIXOTROPH.json VPRO/LSQ/vpro_4379_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo4_sobol_3_MIXOTROPH.json VPRO/LSQ/vpro_43_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo4_sobol_40_MIXOTROPH.json VPRO/LSQ/vpro_440_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo4_sobol_419_MIXOTROPH.json VPRO/LSQ/vpro_4419_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo4_sobol_431_MIXOTROPH.json VPRO/LSQ/vpro_4431_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo4_sobol_483_MIXOTROPH.json VPRO/LSQ/vpro_4483_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo4_sobol_495_MIXOTROPH.json VPRO/LSQ/vpro_4495_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo4_sobol_512_MIXOTROPH.json VPRO/LSQ/vpro_4512_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo4_sobol_524_MIXOTROPH.json VPRO/LSQ/vpro_4524_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo4_sobol_540_MIXOTROPH.json VPRO/LSQ/vpro_4540_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo4_sobol_576_MIXOTROPH.json VPRO/LSQ/vpro_4576_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo4_sobol_591_MIXOTROPH.json VPRO/LSQ/vpro_4591_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo4_sobol_603_MIXOTROPH.json VPRO/LSQ/vpro_4603_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo4_sobol_643_MIXOTROPH.json VPRO/LSQ/vpro_4643_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo4_sobol_688_MIXOTROPH.json VPRO/LSQ/vpro_4688_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo4_sobol_704_MIXOTROPH.json VPRO/LSQ/vpro_4704_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo4_sobol_736_MIXOTROPH.json VPRO/LSQ/vpro_4736_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo4_sobol_752_MIXOTROPH.json VPRO/LSQ/vpro_4752_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo4_sobol_764_MIXOTROPH.json VPRO/LSQ/vpro_4764_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo4_sobol_771_MIXOTROPH.json VPRO/LSQ/vpro_4771_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo4_sobol_796_MIXOTROPH.json VPRO/LSQ/vpro_4796_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo4_sobol_808_MIXOTROPH.json VPRO/LSQ/vpro_4808_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo4_sobol_815_MIXOTROPH.json VPRO/LSQ/vpro_4815_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo4_sobol_844_MIXOTROPH.json VPRO/LSQ/vpro_4844_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo4_sobol_847_MIXOTROPH.json VPRO/LSQ/vpro_4847_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo4_sobol_860_MIXOTROPH.json VPRO/LSQ/vpro_4860_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo4_sobol_911_MIXOTROPH.json VPRO/LSQ/vpro_4911_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo4_sobol_912_MIXOTROPH.json VPRO/LSQ/vpro_4912_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo4_sobol_963_MIXOTROPH.json VPRO/LSQ/vpro_4963_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo4_sobol_96_MIXOTROPH.json VPRO/LSQ/vpro_496_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo4_sobol_975_MIXOTROPH.json VPRO/LSQ/vpro_4975_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo4_sobol_976_MIXOTROPH.json VPRO/LSQ/vpro_4976_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_MIXOTROPH/out/lsq_ponly_MIXOTROPH_shgo4_sobol_995_MIXOTROPH.json VPRO/LSQ/vpro_4995_MIXOTROPH.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo3_sobol_121_OVERFLOW.json VPRO/LSQ/vpro_3121_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo3_sobol_126_OVERFLOW.json VPRO/LSQ/vpro_3126_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo3_sobol_14_OVERFLOW.json VPRO/LSQ/vpro_314_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo3_sobol_153_OVERFLOW.json VPRO/LSQ/vpro_3153_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo3_sobol_169_OVERFLOW.json VPRO/LSQ/vpro_3169_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo3_sobol_173_OVERFLOW.json VPRO/LSQ/vpro_3173_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo3_sobol_174_OVERFLOW.json VPRO/LSQ/vpro_3174_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo3_sobol_1_OVERFLOW.json VPRO/LSQ/vpro_31_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo3_sobol_209_OVERFLOW.json VPRO/LSQ/vpro_3209_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo3_sobol_214_OVERFLOW.json VPRO/LSQ/vpro_3214_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo3_sobol_222_OVERFLOW.json VPRO/LSQ/vpro_3222_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo3_sobol_225_OVERFLOW.json VPRO/LSQ/vpro_3225_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo3_sobol_230_OVERFLOW.json VPRO/LSQ/vpro_3230_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo3_sobol_265_OVERFLOW.json VPRO/LSQ/vpro_3265_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo3_sobol_318_OVERFLOW.json VPRO/LSQ/vpro_3318_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo3_sobol_321_OVERFLOW.json VPRO/LSQ/vpro_3321_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo3_sobol_326_OVERFLOW.json VPRO/LSQ/vpro_3326_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo3_sobol_358_OVERFLOW.json VPRO/LSQ/vpro_3358_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo3_sobol_370_OVERFLOW.json VPRO/LSQ/vpro_3370_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo3_sobol_382_OVERFLOW.json VPRO/LSQ/vpro_3382_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo3_sobol_402_OVERFLOW.json VPRO/LSQ/vpro_3402_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo3_sobol_406_OVERFLOW.json VPRO/LSQ/vpro_3406_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo3_sobol_422_OVERFLOW.json VPRO/LSQ/vpro_3422_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo3_sobol_430_OVERFLOW.json VPRO/LSQ/vpro_3430_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo3_sobol_473_OVERFLOW.json VPRO/LSQ/vpro_3473_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo3_sobol_478_OVERFLOW.json VPRO/LSQ/vpro_3478_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo3_sobol_494_OVERFLOW.json VPRO/LSQ/vpro_3494_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo3_sobol_530_OVERFLOW.json VPRO/LSQ/vpro_3530_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo3_sobol_534_OVERFLOW.json VPRO/LSQ/vpro_3534_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo3_sobol_54_OVERFLOW.json VPRO/LSQ/vpro_354_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo3_sobol_550_OVERFLOW.json VPRO/LSQ/vpro_3550_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo3_sobol_598_OVERFLOW.json VPRO/LSQ/vpro_3598_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo3_sobol_606_OVERFLOW.json VPRO/LSQ/vpro_3606_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo3_sobol_622_OVERFLOW.json VPRO/LSQ/vpro_3622_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo3_sobol_646_OVERFLOW.json VPRO/LSQ/vpro_3646_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo3_sobol_649_OVERFLOW.json VPRO/LSQ/vpro_3649_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo3_sobol_654_OVERFLOW.json VPRO/LSQ/vpro_3654_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo3_sobol_697_OVERFLOW.json VPRO/LSQ/vpro_3697_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo3_sobol_702_OVERFLOW.json VPRO/LSQ/vpro_3702_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo3_sobol_710_OVERFLOW.json VPRO/LSQ/vpro_3710_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo3_sobol_713_OVERFLOW.json VPRO/LSQ/vpro_3713_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo3_sobol_73_OVERFLOW.json VPRO/LSQ/vpro_373_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo3_sobol_753_OVERFLOW.json VPRO/LSQ/vpro_3753_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo3_sobol_758_OVERFLOW.json VPRO/LSQ/vpro_3758_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo3_sobol_77_OVERFLOW.json VPRO/LSQ/vpro_377_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo3_sobol_786_OVERFLOW.json VPRO/LSQ/vpro_3786_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo3_sobol_793_OVERFLOW.json VPRO/LSQ/vpro_3793_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo3_sobol_798_OVERFLOW.json VPRO/LSQ/vpro_3798_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo3_sobol_806_OVERFLOW.json VPRO/LSQ/vpro_3806_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo3_sobol_809_OVERFLOW.json VPRO/LSQ/vpro_3809_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo3_sobol_813_OVERFLOW.json VPRO/LSQ/vpro_3813_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo3_sobol_849_OVERFLOW.json VPRO/LSQ/vpro_3849_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo3_sobol_854_OVERFLOW.json VPRO/LSQ/vpro_3854_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo4_sobol_106_OVERFLOW.json VPRO/LSQ/vpro_4106_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo4_sobol_110_OVERFLOW.json VPRO/LSQ/vpro_4110_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo4_sobol_178_OVERFLOW.json VPRO/LSQ/vpro_4178_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo4_sobol_17_OVERFLOW.json VPRO/LSQ/vpro_417_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo4_sobol_18_OVERFLOW.json VPRO/LSQ/vpro_418_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo4_sobol_193_OVERFLOW.json VPRO/LSQ/vpro_4193_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo4_sobol_194_OVERFLOW.json VPRO/LSQ/vpro_4194_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo4_sobol_274_OVERFLOW.json VPRO/LSQ/vpro_4274_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo4_sobol_281_OVERFLOW.json VPRO/LSQ/vpro_4281_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo4_sobol_285_OVERFLOW.json VPRO/LSQ/vpro_4285_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo4_sobol_302_OVERFLOW.json VPRO/LSQ/vpro_4302_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo4_sobol_338_OVERFLOW.json VPRO/LSQ/vpro_4338_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo4_sobol_34_OVERFLOW.json VPRO/LSQ/vpro_434_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo4_sobol_353_OVERFLOW.json VPRO/LSQ/vpro_4353_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo4_sobol_358_OVERFLOW.json VPRO/LSQ/vpro_4358_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo4_sobol_385_OVERFLOW.json VPRO/LSQ/vpro_4385_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo4_sobol_433_OVERFLOW.json VPRO/LSQ/vpro_4433_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo4_sobol_458_OVERFLOW.json VPRO/LSQ/vpro_4458_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo4_sobol_461_OVERFLOW.json VPRO/LSQ/vpro_4461_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo4_sobol_509_OVERFLOW.json VPRO/LSQ/vpro_4509_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo4_sobol_510_OVERFLOW.json VPRO/LSQ/vpro_4510_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo4_sobol_513_OVERFLOW.json VPRO/LSQ/vpro_4513_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo4_sobol_526_OVERFLOW.json VPRO/LSQ/vpro_4526_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo4_sobol_562_OVERFLOW.json VPRO/LSQ/vpro_4562_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo4_sobol_565_OVERFLOW.json VPRO/LSQ/vpro_4565_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo4_sobol_589_OVERFLOW.json VPRO/LSQ/vpro_4589_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo4_sobol_590_OVERFLOW.json VPRO/LSQ/vpro_4590_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo4_sobol_633_OVERFLOW.json VPRO/LSQ/vpro_4633_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo4_sobol_637_OVERFLOW.json VPRO/LSQ/vpro_4637_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo4_sobol_665_OVERFLOW.json VPRO/LSQ/vpro_4665_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo4_sobol_669_OVERFLOW.json VPRO/LSQ/vpro_4669_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo4_sobol_721_OVERFLOW.json VPRO/LSQ/vpro_4721_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo4_sobol_725_OVERFLOW.json VPRO/LSQ/vpro_4725_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo4_sobol_734_OVERFLOW.json VPRO/LSQ/vpro_4734_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo4_sobol_737_OVERFLOW.json VPRO/LSQ/vpro_4737_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo4_sobol_781_OVERFLOW.json VPRO/LSQ/vpro_4781_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo4_sobol_782_OVERFLOW.json VPRO/LSQ/vpro_4782_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo4_sobol_830_OVERFLOW.json VPRO/LSQ/vpro_4830_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo4_sobol_881_OVERFLOW.json VPRO/LSQ/vpro_4881_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo4_sobol_882_OVERFLOW.json VPRO/LSQ/vpro_4882_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo4_sobol_894_OVERFLOW.json VPRO/LSQ/vpro_4894_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo4_sobol_89_OVERFLOW.json VPRO/LSQ/vpro_489_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo4_sobol_914_OVERFLOW.json VPRO/LSQ/vpro_4914_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo4_sobol_929_OVERFLOW.json VPRO/LSQ/vpro_4929_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo4_sobol_934_OVERFLOW.json VPRO/LSQ/vpro_4934_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo4_sobol_94_OVERFLOW.json VPRO/LSQ/vpro_494_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_OVERFLOW/out/lsq_ponly_OVERFLOW_shgo4_sobol_990_OVERFLOW.json VPRO/LSQ/vpro_4990_OVERFLOW.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo3_sobol_107_ROS.json VPRO/LSQ/vpro_3107_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo3_sobol_135_ROS.json VPRO/LSQ/vpro_3135_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo3_sobol_16_ROS.json VPRO/LSQ/vpro_316_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo3_sobol_187_ROS.json VPRO/LSQ/vpro_3187_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo3_sobol_207_ROS.json VPRO/LSQ/vpro_3207_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo3_sobol_223_ROS.json VPRO/LSQ/vpro_3223_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo3_sobol_24_ROS.json VPRO/LSQ/vpro_324_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo3_sobol_251_ROS.json VPRO/LSQ/vpro_3251_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo3_sobol_255_ROS.json VPRO/LSQ/vpro_3255_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo3_sobol_276_ROS.json VPRO/LSQ/vpro_3276_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo3_sobol_288_ROS.json VPRO/LSQ/vpro_3288_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo3_sobol_303_ROS.json VPRO/LSQ/vpro_3303_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo3_sobol_304_ROS.json VPRO/LSQ/vpro_3304_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo3_sobol_329_ROS.json VPRO/LSQ/vpro_3329_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo3_sobol_352_ROS.json VPRO/LSQ/vpro_3352_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo3_sobol_36_ROS.json VPRO/LSQ/vpro_336_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo3_sobol_387_ROS.json VPRO/LSQ/vpro_3387_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo3_sobol_388_ROS.json VPRO/LSQ/vpro_3388_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo3_sobol_428_ROS.json VPRO/LSQ/vpro_3428_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo3_sobol_432_ROS.json VPRO/LSQ/vpro_3432_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo3_sobol_440_ROS.json VPRO/LSQ/vpro_3440_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo3_sobol_452_ROS.json VPRO/LSQ/vpro_3452_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo3_sobol_468_ROS.json VPRO/LSQ/vpro_3468_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo3_sobol_484_ROS.json VPRO/LSQ/vpro_3484_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo3_sobol_504_ROS.json VPRO/LSQ/vpro_3504_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo3_sobol_511_ROS.json VPRO/LSQ/vpro_3511_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo3_sobol_512_ROS.json VPRO/LSQ/vpro_3512_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo3_sobol_513_ROS.json VPRO/LSQ/vpro_3513_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo3_sobol_527_ROS.json VPRO/LSQ/vpro_3527_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo3_sobol_540_ROS.json VPRO/LSQ/vpro_3540_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo3_sobol_576_ROS.json VPRO/LSQ/vpro_3576_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo3_sobol_59_ROS.json VPRO/LSQ/vpro_359_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo3_sobol_608_ROS.json VPRO/LSQ/vpro_3608_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo3_sobol_612_ROS.json VPRO/LSQ/vpro_3612_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo3_sobol_614_ROS.json VPRO/LSQ/vpro_3614_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo3_sobol_644_ROS.json VPRO/LSQ/vpro_3644_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo3_sobol_656_ROS.json VPRO/LSQ/vpro_3656_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo3_sobol_660_ROS.json VPRO/LSQ/vpro_3660_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo3_sobol_664_ROS.json VPRO/LSQ/vpro_3664_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo3_sobol_665_ROS.json VPRO/LSQ/vpro_3665_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo3_sobol_676_ROS.json VPRO/LSQ/vpro_3676_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo3_sobol_681_ROS.json VPRO/LSQ/vpro_3681_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo3_sobol_703_ROS.json VPRO/LSQ/vpro_3703_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo3_sobol_720_ROS.json VPRO/LSQ/vpro_3720_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo3_sobol_740_ROS.json VPRO/LSQ/vpro_3740_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo3_sobol_747_ROS.json VPRO/LSQ/vpro_3747_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo3_sobol_772_ROS.json VPRO/LSQ/vpro_3772_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo3_sobol_779_ROS.json VPRO/LSQ/vpro_3779_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo3_sobol_803_ROS.json VPRO/LSQ/vpro_3803_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo3_sobol_816_ROS.json VPRO/LSQ/vpro_3816_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo3_sobol_824_ROS.json VPRO/LSQ/vpro_3824_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo3_sobol_831_ROS.json VPRO/LSQ/vpro_3831_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo3_sobol_843_ROS.json VPRO/LSQ/vpro_3843_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo3_sobol_87_ROS.json VPRO/LSQ/vpro_387_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo3_sobol_887_ROS.json VPRO/LSQ/vpro_3887_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo3_sobol_891_ROS.json VPRO/LSQ/vpro_3891_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo3_sobol_95_ROS.json VPRO/LSQ/vpro_395_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo4_sobol_1021_ROS.json VPRO/LSQ/vpro_41021_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo4_sobol_107_ROS.json VPRO/LSQ/vpro_4107_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo4_sobol_10_ROS.json VPRO/LSQ/vpro_410_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo4_sobol_113_ROS.json VPRO/LSQ/vpro_4113_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo4_sobol_12_ROS.json VPRO/LSQ/vpro_412_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo4_sobol_146_ROS.json VPRO/LSQ/vpro_4146_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo4_sobol_149_ROS.json VPRO/LSQ/vpro_4149_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo4_sobol_154_ROS.json VPRO/LSQ/vpro_4154_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo4_sobol_188_ROS.json VPRO/LSQ/vpro_4188_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo4_sobol_218_ROS.json VPRO/LSQ/vpro_4218_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo4_sobol_243_ROS.json VPRO/LSQ/vpro_4243_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo4_sobol_270_ROS.json VPRO/LSQ/vpro_4270_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo4_sobol_282_ROS.json VPRO/LSQ/vpro_4282_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo4_sobol_309_ROS.json VPRO/LSQ/vpro_4309_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo4_sobol_316_ROS.json VPRO/LSQ/vpro_4316_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo4_sobol_334_ROS.json VPRO/LSQ/vpro_4334_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo4_sobol_359_ROS.json VPRO/LSQ/vpro_4359_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo4_sobol_386_ROS.json VPRO/LSQ/vpro_4386_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo4_sobol_426_ROS.json VPRO/LSQ/vpro_4426_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo4_sobol_485_ROS.json VPRO/LSQ/vpro_4485_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo4_sobol_490_ROS.json VPRO/LSQ/vpro_4490_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo4_sobol_511_ROS.json VPRO/LSQ/vpro_4511_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo4_sobol_538_ROS.json VPRO/LSQ/vpro_4538_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo4_sobol_541_ROS.json VPRO/LSQ/vpro_4541_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo4_sobol_586_ROS.json VPRO/LSQ/vpro_4586_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo4_sobol_5_ROS.json VPRO/LSQ/vpro_45_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo4_sobol_642_ROS.json VPRO/LSQ/vpro_4642_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo4_sobol_69_ROS.json VPRO/LSQ/vpro_469_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo4_sobol_739_ROS.json VPRO/LSQ/vpro_4739_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo4_sobol_77_ROS.json VPRO/LSQ/vpro_477_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo4_sobol_781_ROS.json VPRO/LSQ/vpro_4781_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo4_sobol_797_ROS.json VPRO/LSQ/vpro_4797_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo4_sobol_813_ROS.json VPRO/LSQ/vpro_4813_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo4_sobol_829_ROS.json VPRO/LSQ/vpro_4829_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo4_sobol_866_ROS.json VPRO/LSQ/vpro_4866_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo4_sobol_901_ROS.json VPRO/LSQ/vpro_4901_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo4_sobol_902_ROS.json VPRO/LSQ/vpro_4902_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo4_sobol_915_ROS.json VPRO/LSQ/vpro_4915_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo4_sobol_917_ROS.json VPRO/LSQ/vpro_4917_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo4_sobol_928_ROS.json VPRO/LSQ/vpro_4928_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo4_sobol_933_ROS.json VPRO/LSQ/vpro_4933_ROS.json
cp /mnt/beegfs/home/dsher/oweissber/RECYCLE_MODEL/results/lsq_ponly_ROS/out/lsq_ponly_ROS_shgo4_sobol_987_ROS.json VPRO/LSQ/vpro_4987_ROS.json
