mlist = [
'ROS-MIXOTROPH-OVERFLOW-EXOENZYME', 'ROS-MIXOTROPH', 'EXOENZYME-ROS',
            'EXOENZYME-MIXOTROPH', 'OVERFLOW-MIXOTROPH', 'OVERFLOW-EXOENZYME', 'OVERFLOW-ROS',
            'EXOENZYME-ROS-MIXOTROPH', 'OVERFLOW-EXOENZYME-MIXOTROPH',
            'OVERFLOW-ROS-MIXOTROPH', 'OVERFLOW-ROS-EXOENZYME',
            ]




